//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskData()
        {
            this.Users = new HashSet<User>();
        }
    
        public int TaskId { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public int ProjectId { get; set; }
        public string TaskTitle { get; set; }
        public int Priority { get; set; }
        public bool IsEnded { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ParentTask ParentTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
